### ISSUE TITLE
Misaligned/cut-off HUDs

### ISSUE THREAD

**Issue by Warr1024** [regulus79/regulus_mtgamejam_2023#11]
![screenshot_20240120_000725](https://github.com/regulus79/regulus_mtgamejam_2023/assets/324806/25a56fd3-3bfc-4162-b172-18eba8344fb9)
![screenshot_20240120_001015](https://github.com/regulus79/regulus_mtgamejam_2023/assets/324806/151e1bcb-4df8-4dfd-81d3-22df67f71834)

You generally cannot mix HUD scaling modes (e.g. fit-to-screen vs absolute size), or else HUDs don't align correctly under different scaling settings.

**Comment by regulus79** [comment]
Hopefully fixed in https://github.com/regulus79/regulus_mtgamejam_2023/commit/9a4858dc810352399098accdb8d5e72b0a69f67a and https://github.com/regulus79/regulus_mtgamejam_2023/commit/e221c8d04f4294d7004a52eb49417c276c45485a.

I ended up removing the cinematic bars since they just seem way to hard to scale correctly (I had been sort of planning to do this for a while).
For the credits logo, I changed it so that it scales in terms of screen height/width (negative number as scale). However, this may also cause the logo to be squished if the window size is changed.
