### ISSUE TITLE
Possible to bypass both guardian and librarian introduction speech

### ISSUE THREAD

**Issue by Warr1024** [regulus79/regulus_mtgamejam_2023#8]
You can run wide around these people and they won't talk to you.

This isn't necessarily a problem for the guardian, but for the librarian, it does make some of his later dialog a bit more inconsistent.

This could be prevented by designing the map to funnel the player into the dialog area ... or you could decide that this is an intended feature and just be sure to handle the downstream consequences correctly.

**Comment by regulus79** [comment]
It is important for new players to hear the dialogue, but as long as most players actively don't try to avoid the npcs, then hopefully it won't be much of a problem? 

I suppose it could easily be fixed by increasing the view range of the npcs, but unless new players are always missing the dialogue, I think it's probably fine...
